### ISSUE TITLE
Allow writing a non-distributable layer upstream

### ISSUE THREAD

**Issue by gcheadle-vmware** [carvel-dev/imgpkg#63]
# Context

As part of #62 a 'workaround' solution was found to [ggcr's inability to write a non-distributable layer](https://github.com/google/go-containerregistry/blob/72597da50ce903895087828b5fc4b918636366f4/pkg/v1/remote/write.go#L76-L78).

The workaround solution was to write the 'foreign' layers upfront before trying to write the image manifest. 

We decided to proceed with the workaround solution, since there was some urgency behind getting window images working. See https://kubernetes.slack.com/archives/CH8KCCKA5/p1598013615011900

# Description
Create a PR or Issue to https://github.com/google/go-containerregistry to allow writing a non-distributable layer. 
Change imgpkg to use the above change to writing an image manifest that contains a 'foreign' image layer.

# Notes
- There's a [closed issue](https://github.com/google/go-containerregistry/issues/741) that has _some_ background.
- Matt Moore (mattmoor@vmware.com) worked on this library if it's difficult getting traction in the repo

---

## Tasks
- [x] Introduce Option to allow specifying "allow non distributable layers"
- [x] Wherever that option is used, support the allowance 
- - [x] Write (this is all we really need, but the options are also used...)
- - [x] MultiWrite
- [x] Add task to use upstream GGCR functionality _OR_ create a story to do so.

**Comment by StevenLocke** [comment]
[Made the PR](https://github.com/google/go-containerregistry/pull/930) in upstream GGCR. Currently blocked on signing the CLA, unsure if that should be done as an individual or for the company.

After that gets merged, we should use it in imgpkg!

**Comment by aaronshurley** [comment]
Looks like the PR was merged a couple of weeks back but has not been part of a release yet. Let's keep this issue open until we can consume the upstream changes.

**Comment by DennisDenuto** [comment]
go-container registry released 0.4.1 that contains the PR to non-distributable layers

https://github.com/google/go-containerregistry/releases/tag/v0.4.1

**Comment by aaronshurley** [comment]
This issue was resolved in https://github.com/vmware-tanzu/carvel-imgpkg/pull/110 and released in v0.6.0.
